name: Build NixOS Pi 5 Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup QEMU for cross-compile
        uses: docker/setup-qemu-action@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux

      - name: Build sdImage
        run: |
          nix build .#nixosConfigurations.pi5.config.system.build.sdImage \
            --print-build-logs

      - name: Upload sdImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-pi5-sd-image
          path: result/sd-image/*.img.zst
